bind [::]:6053
cache-size 10240
serve-expired yes
dualstack-ip-selection yes

server 119.29.29.29
server 223.5.5.5

nameserver /taobao.com/119.29.29.29
nameserver /jd.com/223.5.5.5
nameserver /bilibili.com/119.29.29.29
